# list available commands
list:
    just --list

# Download the OpenAPI specification for the Beam API
[group('openapi')]
download:
    dotnet beam oapi download --output combinedOpenApi.json --combine-into-one-document

# Update the OpenAPI specification with additional information
[group('openapi')]
update:
    sed -i 's/"summary"/"description"/g' -i combinedOpenApi.json
    jq '.info.title = "Beamable API"' combinedOpenApi.json > new.json
    jq '.info.license = {"name": "MIT"}' new.json > combinedOpenApi.json
    jq '.info.description = "Autogenerated Beamable API"' combinedOpenApi.json > new.json
    rm combinedOpenApi.json
    mv new.json combinedOpenApi.json

# Remove old files
_remove_old:
    rm -rf src && rm -rf docs

# Generate code from the OpenAPI specification
[group('openapi')]
generate: 
    docker run --rm --user "$(id -u):$(id -g)" -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/combinedOpenApi.json -g rust -c /local/package_oapi_config.json -o /local/

# Install dependencies
setup:
    dotnet tool restore

# Apply clippy fixes and formatting
[group('code')]
fix:
    cargo clippy --fix --allow-staged --allow-dirty
    cargo fmt --all

# Validate the generated code
[group('code')]
validate:
    cargo build
    cargo test
    cargo fmt --all -- --check
    cargo clippy -- -D warnings
