/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`object_chat_v2_object_id_get`]
#[derive(Clone, Debug)]
pub struct ObjectChatV2ObjectIdGetParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub scope: Option<String>,
}

/// struct for passing parameters to the method [`object_chat_v2_object_id_messages_post`]
#[derive(Clone, Debug)]
pub struct ObjectChatV2ObjectIdMessagesPostParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub send_message_request: Option<models::SendMessageRequest>,
}

/// struct for passing parameters to the method [`object_chat_v2_object_id_rooms_delete`]
#[derive(Clone, Debug)]
pub struct ObjectChatV2ObjectIdRoomsDeleteParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub leave_room_request: Option<models::LeaveRoomRequest>,
}

/// struct for passing parameters to the method [`object_chat_v2_object_id_rooms_get`]
#[derive(Clone, Debug)]
pub struct ObjectChatV2ObjectIdRoomsGetParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_chat_v2_object_id_rooms_post`]
#[derive(Clone, Debug)]
pub struct ObjectChatV2ObjectIdRoomsPostParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub create_room_request: Option<models::CreateRoomRequest>,
}

/// struct for typed errors of method [`object_chat_v2_object_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectChatV2ObjectIdGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_chat_v2_object_id_messages_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectChatV2ObjectIdMessagesPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_chat_v2_object_id_rooms_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectChatV2ObjectIdRoomsDeleteError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_chat_v2_object_id_rooms_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectChatV2ObjectIdRoomsGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_chat_v2_object_id_rooms_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectChatV2ObjectIdRoomsPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

pub async fn object_chat_v2_object_id_get(
    configuration: &configuration::Configuration,
    params: ObjectChatV2ObjectIdGetParams,
) -> Result<models::GetRoomsResponse, Error<ObjectChatV2ObjectIdGetError>> {
    let uri_str = format!(
        "{}/object/chatV2/{objectId}/",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.scope {
        req_builder = req_builder.query(&[("scope", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetRoomsResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetRoomsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectChatV2ObjectIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_chat_v2_object_id_messages_post(
    configuration: &configuration::Configuration,
    params: ObjectChatV2ObjectIdMessagesPostParams,
) -> Result<models::SendMessageResponse, Error<ObjectChatV2ObjectIdMessagesPostError>> {
    let uri_str = format!(
        "{}/object/chatV2/{objectId}/messages",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.send_message_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SendMessageResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SendMessageResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectChatV2ObjectIdMessagesPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_chat_v2_object_id_rooms_delete(
    configuration: &configuration::Configuration,
    params: ObjectChatV2ObjectIdRoomsDeleteParams,
) -> Result<models::LeaveRoomResponse, Error<ObjectChatV2ObjectIdRoomsDeleteError>> {
    let uri_str = format!(
        "{}/object/chatV2/{objectId}/rooms",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.leave_room_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaveRoomResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaveRoomResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectChatV2ObjectIdRoomsDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_chat_v2_object_id_rooms_get(
    configuration: &configuration::Configuration,
    params: ObjectChatV2ObjectIdRoomsGetParams,
) -> Result<models::GetRoomsResponse, Error<ObjectChatV2ObjectIdRoomsGetError>> {
    let uri_str = format!(
        "{}/object/chatV2/{objectId}/rooms",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetRoomsResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetRoomsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectChatV2ObjectIdRoomsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_chat_v2_object_id_rooms_post(
    configuration: &configuration::Configuration,
    params: ObjectChatV2ObjectIdRoomsPostParams,
) -> Result<models::CreateRoomResponse, Error<ObjectChatV2ObjectIdRoomsPostError>> {
    let uri_str = format!(
        "{}/object/chatV2/{objectId}/rooms",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.create_room_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateRoomResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateRoomResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectChatV2ObjectIdRoomsPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
