/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`object_event_players_object_id_claim_post`]
#[derive(Clone, Debug)]
pub struct ObjectEventPlayersObjectIdClaimPostParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub event_claim_request: Option<models::EventClaimRequest>,
}

/// struct for passing parameters to the method [`object_event_players_object_id_get`]
#[derive(Clone, Debug)]
pub struct ObjectEventPlayersObjectIdGetParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_event_players_object_id_score_put`]
#[derive(Clone, Debug)]
pub struct ObjectEventPlayersObjectIdScorePutParams {
    /// Gamertag of the player.Underlying objectId type is integer in format int64.
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub event_score_request: Option<models::EventScoreRequest>,
}

/// struct for typed errors of method [`object_event_players_object_id_claim_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectEventPlayersObjectIdClaimPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_event_players_object_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectEventPlayersObjectIdGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_event_players_object_id_score_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectEventPlayersObjectIdScorePutError {
    Status400(),
    UnknownValue(serde_json::Value),
}

pub async fn object_event_players_object_id_claim_post(
    configuration: &configuration::Configuration,
    params: ObjectEventPlayersObjectIdClaimPostParams,
) -> Result<models::EventClaimResponse, Error<ObjectEventPlayersObjectIdClaimPostError>> {
    let uri_str = format!(
        "{}/object/event-players/{objectId}/claim",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.event_claim_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EventClaimResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EventClaimResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectEventPlayersObjectIdClaimPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_event_players_object_id_get(
    configuration: &configuration::Configuration,
    params: ObjectEventPlayersObjectIdGetParams,
) -> Result<models::EventPlayerView, Error<ObjectEventPlayersObjectIdGetError>> {
    let uri_str = format!(
        "{}/object/event-players/{objectId}/",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EventPlayerView`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EventPlayerView`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectEventPlayersObjectIdGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_event_players_object_id_score_put(
    configuration: &configuration::Configuration,
    params: ObjectEventPlayersObjectIdScorePutParams,
) -> Result<models::CommonResponse, Error<ObjectEventPlayersObjectIdScorePutError>> {
    let uri_str = format!(
        "{}/object/event-players/{objectId}/score",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.event_score_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectEventPlayersObjectIdScorePutError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
