/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`basic_leaderboards_assignment_get`]
#[derive(Clone, Debug)]
pub struct BasicLeaderboardsAssignmentGetParams {
    pub board_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub join_board: Option<bool>,
}

/// struct for passing parameters to the method [`basic_leaderboards_list_get`]
#[derive(Clone, Debug)]
pub struct BasicLeaderboardsListGetParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub skip: Option<i32>,
    pub limit: Option<i32>,
    pub prefix: Option<String>,
    pub include_partitions: Option<bool>,
}

/// struct for passing parameters to the method [`basic_leaderboards_player_get`]
#[derive(Clone, Debug)]
pub struct BasicLeaderboardsPlayerGetParams {
    pub dbid: i64,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`basic_leaderboards_uid_get`]
#[derive(Clone, Debug)]
pub struct BasicLeaderboardsUidGetParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_assignment_delete`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdAssignmentDeleteParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub leaderboard_remove_cache_entry_request: Option<models::LeaderboardRemoveCacheEntryRequest>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_assignment_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdAssignmentGetParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_delete`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdDeleteParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_details_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdDetailsGetParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub from: Option<i32>,
    pub max: Option<i32>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_entries_delete`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdEntriesDeleteParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_entry_delete`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdEntryDeleteParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub leaderboard_remove_entry_request: Option<models::LeaderboardRemoveEntryRequest>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_entry_put`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdEntryPutParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub leaderboard_add_request: Option<models::LeaderboardAddRequest>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_freeze_delete`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdFreezeDeleteParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_freeze_put`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdFreezePutParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_friends_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdFriendsGetParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_matches_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdMatchesGetParams {
    pub pool_size: i32,
    pub windows: i32,
    pub window_size: i32,
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_membership_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdMembershipGetParams {
    pub player_id: i64,
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_partition_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdPartitionGetParams {
    pub player_id: i64,
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_post`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdPostParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub leaderboard_create_request: Option<models::LeaderboardCreateRequest>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_ranks_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdRanksGetParams {
    pub ids: String,
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_swap_put`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdSwapPutParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub leaderboard_swap_request: Option<models::LeaderboardSwapRequest>,
}

/// struct for passing parameters to the method [`object_leaderboards_object_id_view_get`]
#[derive(Clone, Debug)]
pub struct ObjectLeaderboardsObjectIdViewGetParams {
    /// Leaderboard ID
    pub object_id: String,
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub max: Option<i32>,
    pub focus: Option<i64>,
    pub friends: Option<bool>,
    pub from: Option<i32>,
    pub outlier: Option<i64>,
    pub guild: Option<bool>,
}

/// struct for typed errors of method [`basic_leaderboards_assignment_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicLeaderboardsAssignmentGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_leaderboards_list_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicLeaderboardsListGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_leaderboards_player_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicLeaderboardsPlayerGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_leaderboards_uid_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicLeaderboardsUidGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_assignment_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdAssignmentDeleteError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_assignment_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdAssignmentGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdDeleteError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_details_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdDetailsGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_entries_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdEntriesDeleteError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_entry_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdEntryDeleteError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_entry_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdEntryPutError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_freeze_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdFreezeDeleteError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_freeze_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdFreezePutError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_friends_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdFriendsGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_matches_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdMatchesGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_membership_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdMembershipGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_partition_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdPartitionGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_ranks_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdRanksGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_swap_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdSwapPutError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`object_leaderboards_object_id_view_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ObjectLeaderboardsObjectIdViewGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

pub async fn basic_leaderboards_assignment_get(
    configuration: &configuration::Configuration,
    params: BasicLeaderboardsAssignmentGetParams,
) -> Result<models::LeaderboardAssignmentInfo, Error<BasicLeaderboardsAssignmentGetError>> {
    let uri_str = format!("{}/basic/leaderboards/assignment", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("boardId", &params.board_id.to_string())]);
    if let Some(ref param_value) = params.join_board {
        req_builder = req_builder.query(&[("joinBoard", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardAssignmentInfo`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardAssignmentInfo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicLeaderboardsAssignmentGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_leaderboards_list_get(
    configuration: &configuration::Configuration,
    params: BasicLeaderboardsListGetParams,
) -> Result<models::LeaderboardListResponse, Error<BasicLeaderboardsListGetError>> {
    let uri_str = format!("{}/basic/leaderboards/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.skip {
        req_builder = req_builder.query(&[("skip", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.prefix {
        req_builder = req_builder.query(&[("prefix", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.include_partitions {
        req_builder = req_builder.query(&[("includePartitions", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardListResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardListResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicLeaderboardsListGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_leaderboards_player_get(
    configuration: &configuration::Configuration,
    params: BasicLeaderboardsPlayerGetParams,
) -> Result<models::ListLeaderBoardViewResponse, Error<BasicLeaderboardsPlayerGetError>> {
    let uri_str = format!("{}/basic/leaderboards/player", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("dbid", &params.dbid.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListLeaderBoardViewResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListLeaderBoardViewResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicLeaderboardsPlayerGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_leaderboards_uid_get(
    configuration: &configuration::Configuration,
    params: BasicLeaderboardsUidGetParams,
) -> Result<models::LeaderboardUidResponse, Error<BasicLeaderboardsUidGetError>> {
    let uri_str = format!("{}/basic/leaderboards/uid", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardUidResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardUidResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicLeaderboardsUidGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_assignment_delete(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdAssignmentDeleteParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdAssignmentDeleteError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/assignment",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.leaderboard_remove_cache_entry_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdAssignmentDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_assignment_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdAssignmentGetParams,
) -> Result<models::LeaderboardAssignmentInfo, Error<ObjectLeaderboardsObjectIdAssignmentGetError>>
{
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/assignment",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardAssignmentInfo`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardAssignmentInfo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdAssignmentGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_delete(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdDeleteParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdDeleteError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_details_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdDetailsGetParams,
) -> Result<models::LeaderboardDetails, Error<ObjectLeaderboardsObjectIdDetailsGetError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/details",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.max {
        req_builder = req_builder.query(&[("max", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardDetails`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardDetails`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdDetailsGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_entries_delete(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdEntriesDeleteParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdEntriesDeleteError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/entries",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdEntriesDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_entry_delete(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdEntryDeleteParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdEntryDeleteError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/entry",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.leaderboard_remove_entry_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdEntryDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_entry_put(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdEntryPutParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdEntryPutError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/entry",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.leaderboard_add_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdEntryPutError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_freeze_delete(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdFreezeDeleteParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdFreezeDeleteError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/freeze",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdFreezeDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_freeze_put(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdFreezePutParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdFreezePutError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/freeze",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdFreezePutError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_friends_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdFriendsGetParams,
) -> Result<models::LeaderBoardViewResponse, Error<ObjectLeaderboardsObjectIdFriendsGetError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/friends",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderBoardViewResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderBoardViewResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdFriendsGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_matches_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdMatchesGetParams,
) -> Result<models::MatchMakingMatchesPvpResponse, Error<ObjectLeaderboardsObjectIdMatchesGetError>>
{
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/matches",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("poolSize", &params.pool_size.to_string())]);
    req_builder = req_builder.query(&[("windows", &params.windows.to_string())]);
    req_builder = req_builder.query(&[("windowSize", &params.window_size.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::MatchMakingMatchesPvpResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::MatchMakingMatchesPvpResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdMatchesGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_membership_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdMembershipGetParams,
) -> Result<
    models::LeaderboardMembershipResponse,
    Error<ObjectLeaderboardsObjectIdMembershipGetError>,
> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/membership",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("playerId", &params.player_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardMembershipResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardMembershipResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdMembershipGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_partition_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdPartitionGetParams,
) -> Result<models::LeaderboardPartitionInfo, Error<ObjectLeaderboardsObjectIdPartitionGetError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/partition",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("playerId", &params.player_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderboardPartitionInfo`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderboardPartitionInfo`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdPartitionGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_post(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdPostParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdPostError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.leaderboard_create_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_ranks_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdRanksGetParams,
) -> Result<models::LeaderBoardViewResponse, Error<ObjectLeaderboardsObjectIdRanksGetError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/ranks",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("ids", &params.ids.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderBoardViewResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderBoardViewResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdRanksGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_swap_put(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdSwapPutParams,
) -> Result<models::CommonResponse, Error<ObjectLeaderboardsObjectIdSwapPutError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/swap",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.leaderboard_swap_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdSwapPutError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn object_leaderboards_object_id_view_get(
    configuration: &configuration::Configuration,
    params: ObjectLeaderboardsObjectIdViewGetParams,
) -> Result<models::LeaderBoardViewResponse, Error<ObjectLeaderboardsObjectIdViewGetError>> {
    let uri_str = format!(
        "{}/object/leaderboards/{objectId}/view",
        configuration.base_path,
        objectId = crate::apis::urlencode(params.object_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.max {
        req_builder = req_builder.query(&[("max", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.focus {
        req_builder = req_builder.query(&[("focus", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.friends {
        req_builder = req_builder.query(&[("friends", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.outlier {
        req_builder = req_builder.query(&[("outlier", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.guild {
        req_builder = req_builder.query(&[("guild", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LeaderBoardViewResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LeaderBoardViewResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ObjectLeaderboardsObjectIdViewGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
