/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`basic_notification_channel_post`]
#[derive(Clone, Debug)]
pub struct BasicNotificationChannelPostParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub notification_request: Option<models::NotificationRequest>,
}

/// struct for passing parameters to the method [`basic_notification_custom_post`]
#[derive(Clone, Debug)]
pub struct BasicNotificationCustomPostParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub notification_request: Option<models::NotificationRequest>,
}

/// struct for passing parameters to the method [`basic_notification_game_post`]
#[derive(Clone, Debug)]
pub struct BasicNotificationGamePostParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub notification_request: Option<models::NotificationRequest>,
}

/// struct for passing parameters to the method [`basic_notification_generic_post`]
#[derive(Clone, Debug)]
pub struct BasicNotificationGenericPostParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub notification_request: Option<models::NotificationRequest>,
}

/// struct for passing parameters to the method [`basic_notification_get`]
#[derive(Clone, Debug)]
pub struct BasicNotificationGetParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
}

/// struct for passing parameters to the method [`basic_notification_player_post`]
#[derive(Clone, Debug)]
pub struct BasicNotificationPlayerPostParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub notification_request: Option<models::NotificationRequest>,
}

/// struct for passing parameters to the method [`basic_notification_server_post`]
#[derive(Clone, Debug)]
pub struct BasicNotificationServerPostParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub server_event: Option<models::ServerEvent>,
}

/// struct for passing parameters to the method [`basic_notification_service_post`]
#[derive(Clone, Debug)]
pub struct BasicNotificationServicePostParams {
    /// Override the Gamer Tag of the player. This is generally inferred by the auth token.
    pub x_beam_gamertag: Option<String>,
    pub server_event: Option<models::ServerEvent>,
}

/// struct for typed errors of method [`basic_notification_channel_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationChannelPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_notification_custom_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationCustomPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_notification_game_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationGamePostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_notification_generic_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationGenericPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_notification_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationGetError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_notification_player_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationPlayerPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_notification_server_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationServerPostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`basic_notification_service_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicNotificationServicePostError {
    Status400(),
    UnknownValue(serde_json::Value),
}

pub async fn basic_notification_channel_post(
    configuration: &configuration::Configuration,
    params: BasicNotificationChannelPostParams,
) -> Result<models::CommonResponse, Error<BasicNotificationChannelPostError>> {
    let uri_str = format!("{}/basic/notification/channel", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.notification_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationChannelPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_notification_custom_post(
    configuration: &configuration::Configuration,
    params: BasicNotificationCustomPostParams,
) -> Result<models::CommonResponse, Error<BasicNotificationCustomPostError>> {
    let uri_str = format!("{}/basic/notification/custom", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.notification_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationCustomPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_notification_game_post(
    configuration: &configuration::Configuration,
    params: BasicNotificationGamePostParams,
) -> Result<models::CommonResponse, Error<BasicNotificationGamePostError>> {
    let uri_str = format!("{}/basic/notification/game", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.notification_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationGamePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_notification_generic_post(
    configuration: &configuration::Configuration,
    params: BasicNotificationGenericPostParams,
) -> Result<models::CommonResponse, Error<BasicNotificationGenericPostError>> {
    let uri_str = format!("{}/basic/notification/generic", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.notification_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationGenericPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_notification_get(
    configuration: &configuration::Configuration,
    params: BasicNotificationGetParams,
) -> Result<models::SubscriberDetailsResponse, Error<BasicNotificationGetError>> {
    let uri_str = format!("{}/basic/notification/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubscriberDetailsResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SubscriberDetailsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_notification_player_post(
    configuration: &configuration::Configuration,
    params: BasicNotificationPlayerPostParams,
) -> Result<models::CommonResponse, Error<BasicNotificationPlayerPostError>> {
    let uri_str = format!("{}/basic/notification/player", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.notification_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationPlayerPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_notification_server_post(
    configuration: &configuration::Configuration,
    params: BasicNotificationServerPostParams,
) -> Result<models::CommonResponse, Error<BasicNotificationServerPostError>> {
    let uri_str = format!("{}/basic/notification/server", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.server_event);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationServerPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn basic_notification_service_post(
    configuration: &configuration::Configuration,
    params: BasicNotificationServicePostParams,
) -> Result<models::CommonResponse, Error<BasicNotificationServicePostError>> {
    let uri_str = format!("{}/basic/notification/service", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };
    req_builder = req_builder.json(&params.server_event);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CommonResponse`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CommonResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BasicNotificationServicePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
