/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`api_players_player_id_lobbies_delete`]
#[derive(Clone, Debug)]
pub struct ApiPlayersPlayerIdLobbiesDeleteParams {
    /// Player Id
    pub player_id: String,
    /// Override the playerId of the requester. This is only necessary when not using a JWT bearer token.
    pub x_beam_gamertag: Option<String>,
    /// Set the request timeout in seconds. Defaults to 10 seconds.
    pub x_beam_timeout: Option<i32>,
}

/// struct for passing parameters to the method [`api_players_player_id_lobbies_get`]
#[derive(Clone, Debug)]
pub struct ApiPlayersPlayerIdLobbiesGetParams {
    /// Player Id
    pub player_id: String,
    /// Override the playerId of the requester. This is only necessary when not using a JWT bearer token.
    pub x_beam_gamertag: Option<String>,
    /// Set the request timeout in seconds. Defaults to 10 seconds.
    pub x_beam_timeout: Option<i32>,
}

/// struct for typed errors of method [`api_players_player_id_lobbies_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPlayersPlayerIdLobbiesDeleteError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`api_players_player_id_lobbies_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiPlayersPlayerIdLobbiesGetError {
    UnknownValue(serde_json::Value),
}

/// If the requested player is in a lobby, remove the player
pub async fn api_players_player_id_lobbies_delete(
    configuration: &configuration::Configuration,
    params: ApiPlayersPlayerIdLobbiesDeleteParams,
) -> Result<serde_json::Value, Error<ApiPlayersPlayerIdLobbiesDeleteError>> {
    let uri_str = format!(
        "{}/api/players/{playerId}/lobbies",
        configuration.base_path,
        playerId = crate::apis::urlencode(params.player_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(param_value) = params.x_beam_timeout {
        req_builder = req_builder.header("X-BEAM-TIMEOUT", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `serde_json::Value`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `serde_json::Value`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPlayersPlayerIdLobbiesDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Fetch the requested player's lobby information
pub async fn api_players_player_id_lobbies_get(
    configuration: &configuration::Configuration,
    params: ApiPlayersPlayerIdLobbiesGetParams,
) -> Result<models::Lobby, Error<ApiPlayersPlayerIdLobbiesGetError>> {
    let uri_str = format!(
        "{}/api/players/{playerId}/lobbies",
        configuration.base_path,
        playerId = crate::apis::urlencode(params.player_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = params.x_beam_gamertag {
        req_builder = req_builder.header("X-BEAM-GAMERTAG", param_value.to_string());
    }
    if let Some(param_value) = params.x_beam_timeout {
        req_builder = req_builder.header("X-BEAM-TIMEOUT", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-BEAM-SCOPE", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Lobby`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Lobby`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ApiPlayersPlayerIdLobbiesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
