/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2AuthCodeRequest {
    #[serde(
        rename = "accountId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_id: Option<Option<String>>,
    #[serde(
        rename = "redirectUri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redirect_uri: Option<Option<String>>,
    #[serde(
        rename = "scopes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scopes: Option<Option<Vec<String>>>,
    #[serde(
        rename = "customerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_id: Option<Option<String>>,
    #[serde(
        rename = "realmId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub realm_id: Option<Option<String>>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::AuthV2ContextInfo>>,
}

impl AuthV2AuthCodeRequest {
    pub fn new() -> AuthV2AuthCodeRequest {
        AuthV2AuthCodeRequest {
            account_id: None,
            redirect_uri: None,
            scopes: None,
            customer_id: None,
            realm_id: None,
            context: None,
        }
    }
}
