/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2RefreshTokenAuthRequest {
    #[serde(
        rename = "refreshToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_token: Option<Option<String>>,
    #[serde(
        rename = "customerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_id: Option<Option<String>>,
    #[serde(
        rename = "realmId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub realm_id: Option<Option<String>>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::AuthV2ContextInfo>>,
}

impl AuthV2RefreshTokenAuthRequest {
    pub fn new() -> AuthV2RefreshTokenAuthRequest {
        AuthV2RefreshTokenAuthRequest {
            refresh_token: None,
            customer_id: None,
            realm_id: None,
            context: None,
        }
    }
}
