/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2RevokeRefreshTokensRequest {
    #[serde(rename = "tokens")]
    pub tokens: Vec<String>,
}

impl AuthV2RevokeRefreshTokensRequest {
    pub fn new(tokens: Vec<String>) -> AuthV2RevokeRefreshTokensRequest {
        AuthV2RevokeRefreshTokensRequest { tokens }
    }
}
