/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2AuthCode {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "accountId")]
    pub account_id: i64,
    #[serde(rename = "redirectUri")]
    pub redirect_uri: String,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(
        rename = "scopes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scopes: Option<Option<Vec<String>>>,
    #[serde(
        rename = "ttl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ttl: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl AuthV2AuthCode {
    pub fn new(code: String, account_id: i64, redirect_uri: String) -> AuthV2AuthCode {
        AuthV2AuthCode {
            code,
            account_id,
            redirect_uri,
            created_at: None,
            scopes: None,
            ttl: None,
        }
    }
}
