/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2ExternalAuthRequest {
    #[serde(
        rename = "provider",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub provider: Option<Option<String>>,
    #[serde(
        rename = "providerNamespace",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub provider_namespace: Option<Option<String>>,
    #[serde(
        rename = "hasProviderNamespace",
        skip_serializing_if = "Option::is_none"
    )]
    pub has_provider_namespace: Option<bool>,
    #[serde(
        rename = "token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub token: Option<Option<String>>,
    #[serde(rename = "challengeSolution", skip_serializing_if = "Option::is_none")]
    pub challenge_solution: Option<Box<models::AuthV2ChallengeSolution>>,
    #[serde(
        rename = "scope",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scope: Option<Option<String>>,
    #[serde(
        rename = "customerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_id: Option<Option<String>>,
    #[serde(
        rename = "realmId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub realm_id: Option<Option<String>>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::AuthV2ContextInfo>>,
}

impl AuthV2ExternalAuthRequest {
    pub fn new() -> AuthV2ExternalAuthRequest {
        AuthV2ExternalAuthRequest {
            provider: None,
            provider_namespace: None,
            has_provider_namespace: None,
            token: None,
            challenge_solution: None,
            scope: None,
            customer_id: None,
            realm_id: None,
            context: None,
        }
    }
}
