/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2ExternalAuthResponse {
    #[serde(
        rename = "accessToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub access_token: Option<Option<String>>,
    #[serde(rename = "hasAccessToken", skip_serializing_if = "Option::is_none")]
    pub has_access_token: Option<bool>,
    #[serde(
        rename = "refreshToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_token: Option<Option<String>>,
    #[serde(rename = "hasRefreshToken", skip_serializing_if = "Option::is_none")]
    pub has_refresh_token: Option<bool>,
    #[serde(
        rename = "challengeToken",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub challenge_token: Option<Option<String>>,
    #[serde(rename = "hasChallengeToken", skip_serializing_if = "Option::is_none")]
    pub has_challenge_token: Option<bool>,
    #[serde(rename = "expiresInMs", skip_serializing_if = "Option::is_none")]
    pub expires_in_ms: Option<i64>,
    #[serde(rename = "hasExpiresInMs", skip_serializing_if = "Option::is_none")]
    pub has_expires_in_ms: Option<bool>,
}

impl AuthV2ExternalAuthResponse {
    pub fn new() -> AuthV2ExternalAuthResponse {
        AuthV2ExternalAuthResponse {
            access_token: None,
            has_access_token: None,
            refresh_token: None,
            has_refresh_token: None,
            challenge_token: None,
            has_challenge_token: None,
            expires_in_ms: None,
            has_expires_in_ms: None,
        }
    }
}
