/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2OpenIdConfigResponse {
    #[serde(rename = "issuer")]
    pub issuer: String,
    #[serde(rename = "jwks_uri")]
    pub jwks_uri: String,
}

impl AuthV2OpenIdConfigResponse {
    pub fn new(issuer: String, jwks_uri: String) -> AuthV2OpenIdConfigResponse {
        AuthV2OpenIdConfigResponse { issuer, jwks_uri }
    }
}
