/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthV2JsonWebKeySet {
    #[serde(
        rename = "keys",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub keys: Option<Option<Vec<models::AuthV2JsonWebKey>>>,
}

impl AuthV2JsonWebKeySet {
    pub fn new() -> AuthV2JsonWebKeySet {
        AuthV2JsonWebKeySet { keys: None }
    }
}
