/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchReadStatsResponse {
    #[serde(rename = "results")]
    pub results: Vec<serde_json::Value>,
}

impl BatchReadStatsResponse {
    pub fn new(results: Vec<serde_json::Value>) -> BatchReadStatsResponse {
        BatchReadStatsResponse {
            results,
        }
    }
}

