/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchWriteItem {
    #[serde(rename = "target")]
    pub target: Box<models::StatsTarget>,
    #[serde(rename = "request")]
    pub request: Box<models::SetStatsRequest>,
}

impl BatchWriteItem {
    pub fn new(target: models::StatsTarget, request: models::SetStatsRequest) -> BatchWriteItem {
        BatchWriteItem {
            target: Box::new(target),
            request: Box::new(request),
        }
    }
}
