/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchWriteRequest {
    #[serde(rename = "requests")]
    pub requests: Vec<models::BatchWriteItem>,
}

impl BatchWriteRequest {
    pub fn new(requests: Vec<models::BatchWriteItem>) -> BatchWriteRequest {
        BatchWriteRequest { requests }
    }
}
