/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoActorServiceStorageReference {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "storageType", skip_serializing_if = "Option::is_none")]
    pub storage_type: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "templateId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<Option<String>>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
}

impl BeamoActorServiceStorageReference {
    pub fn new() -> BeamoActorServiceStorageReference {
        BeamoActorServiceStorageReference {
            id: None,
            storage_type: None,
            enabled: None,
            template_id: None,
            archived: None,
            checksum: None,
        }
    }
}

