/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2PaNamespace {
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl BeamoV2PaNamespace {
    pub fn new(namespace: String, r#type: String) -> BeamoV2PaNamespace {
        BeamoV2PaNamespace {
            namespace,
            r#type,
        }
    }
}

