/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoActorPostManifestRequest {
    #[serde(rename = "manifest", skip_serializing_if = "Option::is_none")]
    pub manifest: Option<Vec<models::BeamoActorServiceReference>>,
    #[serde(rename = "storageReferences", skip_serializing_if = "Option::is_none")]
    pub storage_references: Option<Vec<models::BeamoActorServiceStorageReference>>,
    #[serde(rename = "comments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comments: Option<Option<String>>,
    #[serde(rename = "autoDeploy", skip_serializing_if = "Option::is_none")]
    pub auto_deploy: Option<bool>,
}

impl BeamoActorPostManifestRequest {
    pub fn new() -> BeamoActorPostManifestRequest {
        BeamoActorPostManifestRequest {
            manifest: None,
            storage_references: None,
            comments: None,
            auto_deploy: None,
        }
    }
}

