/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2LogContextRule {
    #[serde(rename = "ruleId", skip_serializing_if = "Option::is_none")]
    pub rule_id: Option<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::BeamoV2LogContextRuleAuthor>>,
    #[serde(rename = "whoLastEdit", skip_serializing_if = "Option::is_none")]
    pub who_last_edit: Option<Box<models::BeamoV2LogContextRuleAuthor>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    #[serde(
        rename = "expiresAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<i64>>,
    #[serde(rename = "logLevel")]
    pub log_level: models::BeamoV2LogLevel,
    #[serde(rename = "ruleFilters")]
    pub rule_filters: Vec<models::BeamoV2ContextRuleFilter>,
}

impl BeamoV2LogContextRule {
    pub fn new(
        enabled: bool,
        log_level: models::BeamoV2LogLevel,
        rule_filters: Vec<models::BeamoV2ContextRuleFilter>,
    ) -> BeamoV2LogContextRule {
        BeamoV2LogContextRule {
            rule_id: None,
            enabled,
            name: None,
            description: None,
            author: None,
            who_last_edit: None,
            created_at: None,
            updated_at: None,
            expires_at: None,
            log_level,
            rule_filters,
        }
    }
}
