/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BeamoV2OrderDirection {
    #[serde(rename = "Desc")]
    Desc,
    #[serde(rename = "Asc")]
    Asc,

}

impl std::fmt::Display for BeamoV2OrderDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Desc => write!(f, "Desc"),
            Self::Asc => write!(f, "Asc"),
        }
    }
}

impl Default for BeamoV2OrderDirection {
    fn default() -> BeamoV2OrderDirection {
        Self::Desc
    }
}

