/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2ServiceStorageStatus {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "storageType", skip_serializing_if = "Option::is_none")]
    pub storage_type: Option<String>,
    #[serde(rename = "isRunning", skip_serializing_if = "Option::is_none")]
    pub is_running: Option<bool>,
    #[serde(rename = "isCurrent", skip_serializing_if = "Option::is_none")]
    pub is_current: Option<bool>,
}

impl BeamoV2ServiceStorageStatus {
    pub fn new() -> BeamoV2ServiceStorageStatus {
        BeamoV2ServiceStorageStatus {
            id: None,
            storage_type: None,
            is_running: None,
            is_current: None,
        }
    }
}

