/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2DatabaseMeasurements {
    #[serde(rename = "databaseName")]
    pub database_name: String,
    #[serde(rename = "granularity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub granularity: Option<Option<String>>,
    #[serde(rename = "groupId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<Option<String>>,
    #[serde(rename = "hostId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub host_id: Option<Option<String>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::BeamoV2Link>>,
    #[serde(rename = "measurements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub measurements: Option<Option<Vec<models::BeamoV2DatabaseMeasurement>>>,
    #[serde(rename = "processId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub process_id: Option<Option<String>>,
    #[serde(rename = "start", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub start: Option<Option<String>>,
    #[serde(rename = "end", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end: Option<Option<String>>,
}

impl BeamoV2DatabaseMeasurements {
    pub fn new(database_name: String) -> BeamoV2DatabaseMeasurements {
        BeamoV2DatabaseMeasurements {
            database_name,
            granularity: None,
            group_id: None,
            host_id: None,
            links: None,
            measurements: None,
            process_id: None,
            start: None,
            end: None,
        }
    }
}

