/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2PaSlowQuery {
    #[serde(rename = "line")]
    pub line: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
}

impl BeamoV2PaSlowQuery {
    pub fn new(line: String, namespace: String) -> BeamoV2PaSlowQuery {
        BeamoV2PaSlowQuery {
            line,
            namespace,
        }
    }
}

