/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2GetManifestsResponse {
    #[serde(rename = "manifests", skip_serializing_if = "Option::is_none")]
    pub manifests: Option<Vec<models::BeamoV2Manifest>>,
}

impl BeamoV2GetManifestsResponse {
    pub fn new() -> BeamoV2GetManifestsResponse {
        BeamoV2GetManifestsResponse {
            manifests: None,
        }
    }
}

