/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoBasicServiceDependencyReference {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "storageType")]
    pub storage_type: String,
}

impl BeamoBasicServiceDependencyReference {
    pub fn new(id: String, storage_type: String) -> BeamoBasicServiceDependencyReference {
        BeamoBasicServiceDependencyReference {
            id,
            storage_type,
        }
    }
}

