/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2ServiceStatus {
    #[serde(rename = "serviceName", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    #[serde(rename = "running", skip_serializing_if = "Option::is_none")]
    pub running: Option<bool>,
    #[serde(rename = "imageId", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<String>,
    #[serde(rename = "isCurrent", skip_serializing_if = "Option::is_none")]
    pub is_current: Option<bool>,
    #[serde(rename = "serviceDependencyReferences", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_dependency_references: Option<Option<Vec<models::BeamoV2ServiceDependencyReference>>>,
}

impl BeamoV2ServiceStatus {
    pub fn new() -> BeamoV2ServiceStatus {
        BeamoV2ServiceStatus {
            service_name: None,
            running: None,
            image_id: None,
            is_current: None,
            service_dependency_references: None,
        }
    }
}

