/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoV2GetStatusResponse {
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<models::BeamoV2ServiceStatus>>,
    #[serde(rename = "isCurrent", skip_serializing_if = "Option::is_none")]
    pub is_current: Option<bool>,
    #[serde(rename = "storageStatuses", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_statuses: Option<Option<Vec<models::BeamoV2ServiceStorageStatus>>>,
}

impl BeamoV2GetStatusResponse {
    pub fn new() -> BeamoV2GetStatusResponse {
        BeamoV2GetStatusResponse {
            services: None,
            is_current: None,
            storage_statuses: None,
        }
    }
}

