/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeamoActorDataPoint {
    #[serde(rename = "timeStamp", skip_serializing_if = "Option::is_none")]
    pub time_stamp: Option<String>,
    #[serde(rename = "value")]
    pub value: f64,
}

impl BeamoActorDataPoint {
    pub fn new(value: f64) -> BeamoActorDataPoint {
        BeamoActorDataPoint {
            time_stamp: None,
            value,
        }
    }
}

