/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum BeamoV2LogProvider {
    #[serde(rename = "Cloudwatch")]
    #[default]
    Cloudwatch,
    #[serde(rename = "Clickhouse")]
    Clickhouse,
}

impl std::fmt::Display for BeamoV2LogProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cloudwatch => write!(f, "Cloudwatch"),
            Self::Clickhouse => write!(f, "Clickhouse"),
        }
    }
}
