/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelInviteToParty {
    #[serde(rename = "playerId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub player_id: Option<Option<String>>,
}

impl CancelInviteToParty {
    pub fn new() -> CancelInviteToParty {
        CancelInviteToParty {
            player_id: None,
        }
    }
}

