/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClearStatusRequest {
    #[serde(rename = "store")]
    pub store: String,
}

impl ClearStatusRequest {
    pub fn new(store: String) -> ClearStatusRequest {
        ClearStatusRequest {
            store,
        }
    }
}

