/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentBasicGetManifestRequest {
    /// ID of the content manifest
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// UID of the content manifest
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
}

impl ContentBasicGetManifestRequest {
    pub fn new() -> ContentBasicGetManifestRequest {
        ContentBasicGetManifestRequest {
            id: None,
            uid: None,
        }
    }
}

