/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentBasicManifestChecksums {
    #[serde(rename = "manifests")]
    pub manifests: Vec<models::ContentBasicManifestChecksum>,
}

impl ContentBasicManifestChecksums {
    pub fn new(manifests: Vec<models::ContentBasicManifestChecksum>) -> ContentBasicManifestChecksums {
        ContentBasicManifestChecksums {
            manifests,
        }
    }
}

