/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRealmRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "plan",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub plan: Option<Option<String>>,
    #[serde(
        rename = "sharded",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sharded: Option<Option<bool>>,
    #[serde(
        rename = "parent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent: Option<Option<String>>,
    #[serde(
        rename = "isHidden",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_hidden: Option<Option<bool>>,
}

impl CreateRealmRequest {
    pub fn new(name: String) -> CreateRealmRequest {
        CreateRealmRequest {
            name,
            plan: None,
            sharded: None,
            parent: None,
            is_hidden: None,
        }
    }
}
