/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrencyDelta {
    #[serde(rename = "before")]
    pub before: i64,
    #[serde(rename = "after")]
    pub after: i64,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, models::PropertyDelta>>,
}

impl CurrencyDelta {
    pub fn new(before: i64, after: i64) -> CurrencyDelta {
        CurrencyDelta {
            before,
            after,
            properties: None,
        }
    }
}
