/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerActorRealmConfiguration {
    #[serde(rename = "environment")]
    pub environment: String,
    #[serde(rename = "websocketConfig")]
    pub websocket_config: Box<models::CustomerActorWebSocketConfiguration>,
    #[serde(rename = "microserviceUri")]
    pub microservice_uri: String,
    #[serde(rename = "microserviceEcrUri")]
    pub microservice_ecr_uri: String,
    #[serde(rename = "portalUri")]
    pub portal_uri: String,
    #[serde(rename = "storageBrowserUri")]
    pub storage_browser_uri: String,
}

impl CustomerActorRealmConfiguration {
    pub fn new(environment: String, websocket_config: models::CustomerActorWebSocketConfiguration, microservice_uri: String, microservice_ecr_uri: String, portal_uri: String, storage_browser_uri: String) -> CustomerActorRealmConfiguration {
        CustomerActorRealmConfiguration {
            environment,
            websocket_config: Box::new(websocket_config),
            microservice_uri,
            microservice_ecr_uri,
            portal_uri,
            storage_browser_uri,
        }
    }
}

