/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerActorNewCustomerRequest {
    #[serde(rename = "realmName")]
    pub realm_name: String,
    #[serde(rename = "customerName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_name: Option<Option<String>>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "hierarchy", skip_serializing_if = "Option::is_none")]
    pub hierarchy: Option<bool>,
    #[serde(rename = "alias", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alias: Option<Option<String>>,
}

impl CustomerActorNewCustomerRequest {
    pub fn new(realm_name: String, email: String, password: String) -> CustomerActorNewCustomerRequest {
        CustomerActorNewCustomerRequest {
            realm_name,
            customer_name: None,
            email,
            password,
            hierarchy: None,
            alias: None,
        }
    }
}

