/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerActorPromoteRealmResponse {
    #[serde(rename = "sourceRealmId")]
    pub source_realm_id: String,
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<models::CustomerActorPromotionScope>>,
}

impl CustomerActorPromoteRealmResponse {
    pub fn new(source_realm_id: String) -> CustomerActorPromoteRealmResponse {
        CustomerActorPromoteRealmResponse {
            source_realm_id,
            scopes: None,
        }
    }
}

