/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerViewResponse {
    #[serde(rename = "customer")]
    pub customer: Box<models::CustomerView>,
}

impl CustomerViewResponse {
    pub fn new(customer: models::CustomerView) -> CustomerViewResponse {
        CustomerViewResponse {
            customer: Box::new(customer),
        }
    }
}

