/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerActorNewGameRequest {
    #[serde(rename = "gameName")]
    pub game_name: String,
    #[serde(
        rename = "isHidden",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_hidden: Option<Option<bool>>,
}

impl CustomerActorNewGameRequest {
    pub fn new(game_name: String) -> CustomerActorNewGameRequest {
        CustomerActorNewGameRequest {
            game_name,
            is_hidden: None,
        }
    }
}
