/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerActorCustomerView {
    #[serde(rename = "customerId")]
    pub customer_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "alias", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alias: Option<Option<String>>,
    #[serde(rename = "realms", skip_serializing_if = "Option::is_none")]
    pub realms: Option<Vec<models::RealmView>>,
}

impl CustomerActorCustomerView {
    pub fn new(customer_id: String, name: String) -> CustomerActorCustomerView {
        CustomerActorCustomerView {
            customer_id,
            name,
            alias: None,
            realms: None,
        }
    }
}

