/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerActorRealmConfigSaveRequest {
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<std::collections::HashMap<String, String>>,
}

impl CustomerActorRealmConfigSaveRequest {
    pub fn new() -> CustomerActorRealmConfigSaveRequest {
        CustomerActorRealmConfigSaveRequest {
            config: None,
        }
    }
}

