/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetManifestDiffsRequest {
    #[serde(rename = "manifestId")]
    pub manifest_id: String,
    #[serde(rename = "fromUid", skip_serializing_if = "Option::is_none")]
    pub from_uid: Option<String>,
    #[serde(rename = "toUid", skip_serializing_if = "Option::is_none")]
    pub to_uid: Option<String>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    #[serde(rename = "fromDate", skip_serializing_if = "Option::is_none")]
    pub from_date: Option<i64>,
    #[serde(rename = "toDate", skip_serializing_if = "Option::is_none")]
    pub to_date: Option<i64>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl GetManifestDiffsRequest {
    pub fn new(manifest_id: String) -> GetManifestDiffsRequest {
        GetManifestDiffsRequest {
            manifest_id,
            from_uid: None,
            to_uid: None,
            offset: None,
            from_date: None,
            to_date: None,
            limit: None,
        }
    }
}

