/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetManifestDiffsResponse {
    #[serde(rename = "manifestId")]
    pub manifest_id: String,
    #[serde(rename = "diffs")]
    pub diffs: Vec<models::ManifestDiffSummary>,
    #[serde(rename = "hasMore")]
    pub has_more: bool,
    #[serde(rename = "totalCount")]
    pub total_count: i32,
}

impl GetManifestDiffsResponse {
    pub fn new(manifest_id: String, diffs: Vec<models::ManifestDiffSummary>, has_more: bool, total_count: i32) -> GetManifestDiffsResponse {
        GetManifestDiffsResponse {
            manifest_id,
            diffs,
            has_more,
            total_count,
        }
    }
}

