/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContentRequest {
    #[serde(rename = "contentId")]
    pub content_id: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl GetContentRequest {
    pub fn new(content_id: String, version: String) -> GetContentRequest {
        GetContentRequest {
            content_id,
            version,
        }
    }
}

