/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStatusForGroupsResponse {
    #[serde(rename = "statuses")]
    pub statuses: Vec<models::GroupStatus>,
    #[serde(rename = "contentId")]
    pub content_id: String,
}

impl GetStatusForGroupsResponse {
    pub fn new(statuses: Vec<models::GroupStatus>, content_id: String) -> GetStatusForGroupsResponse {
        GetStatusForGroupsResponse {
            statuses,
            content_id,
        }
    }
}

