/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupUsersObjectFederationInfo {
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<models::OptionalJsonNodeWrapper>>,
}

impl GroupUsersObjectFederationInfo {
    pub fn new(service: String, namespace: String) -> GroupUsersObjectFederationInfo {
        GroupUsersObjectFederationInfo {
            service,
            namespace,
            settings: None,
        }
    }
}

