/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InventoryObjectFederationInfo {
    #[serde(rename = "service")]
    pub service: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
}

impl InventoryObjectFederationInfo {
    pub fn new(service: String, namespace: String) -> InventoryObjectFederationInfo {
        InventoryObjectFederationInfo {
            service,
            namespace,
        }
    }
}

