/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemDeltas {
    #[serde(rename = "created")]
    pub created: Vec<models::ItemPropertiesDelta>,
    #[serde(rename = "updated")]
    pub updated: Vec<models::ItemPropertiesDelta>,
    #[serde(rename = "deleted")]
    pub deleted: Vec<models::ItemPropertiesDelta>,
}

impl ItemDeltas {
    pub fn new(
        created: Vec<models::ItemPropertiesDelta>,
        updated: Vec<models::ItemPropertiesDelta>,
        deleted: Vec<models::ItemPropertiesDelta>,
    ) -> ItemDeltas {
        ItemDeltas {
            created,
            updated,
            deleted,
        }
    }
}
