/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManifestDiffSummary {
    #[serde(rename = "affectedContentIds")]
    pub affected_content_ids: Vec<String>,
    #[serde(rename = "manifestUid")]
    pub manifest_uid: String,
    #[serde(rename = "publishedByName", skip_serializing_if = "Option::is_none")]
    pub published_by_name: Option<String>,
    #[serde(rename = "publishedBy", skip_serializing_if = "Option::is_none")]
    pub published_by: Option<String>,
    #[serde(rename = "createdDate")]
    pub created_date: i64,
}

impl ManifestDiffSummary {
    pub fn new(
        affected_content_ids: Vec<String>,
        manifest_uid: String,
        created_date: i64,
    ) -> ManifestDiffSummary {
        ManifestDiffSummary {
            affected_content_ids,
            manifest_uid,
            published_by_name: None,
            published_by: None,
            created_date,
        }
    }
}
