/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObjectRequest {
    #[serde(rename = "objectKey")]
    pub object_key: String,
}

impl ObjectRequest {
    pub fn new(object_key: String) -> ObjectRequest {
        ObjectRequest {
            object_key,
        }
    }
}

