/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OtelAuthConfig {
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<String>>,
}

impl OtelAuthConfig {
    pub fn new(endpoint: String, username: String, password: String) -> OtelAuthConfig {
        OtelAuthConfig {
            endpoint,
            username,
            password,
            expires_at: None,
        }
    }
}

