/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Party {
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    #[serde(
        rename = "restriction",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub restriction: Option<Option<String>>,
    #[serde(
        rename = "leader",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub leader: Option<Option<String>>,
    #[serde(
        rename = "members",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub members: Option<Option<Vec<String>>>,
    #[serde(rename = "maxSize", skip_serializing_if = "Option::is_none")]
    pub max_size: Option<i32>,
    #[serde(
        rename = "pendingInvites",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pending_invites: Option<Option<Vec<String>>>,
    #[serde(
        rename = "created",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "membersTags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub members_tags: Option<Option<std::collections::HashMap<String, models::TagList>>>,
}

impl Party {
    pub fn new() -> Party {
        Party {
            id: None,
            restriction: None,
            leader: None,
            members: None,
            max_size: None,
            pending_invites: None,
            created: None,
            members_tags: None,
        }
    }
}
