/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentStatus {
    #[serde(rename = "Free")]
    Free,
    #[serde(rename = "Paid")]
    Paid,
    #[serde(rename = "Banned")]
    Banned,

}

impl std::fmt::Display for PaymentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Free => write!(f, "Free"),
            Self::Paid => write!(f, "Paid"),
            Self::Banned => write!(f, "Banned"),
        }
    }
}

impl Default for PaymentStatus {
    fn default() -> PaymentStatus {
        Self::Free
    }
}

