/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreSignedUrlsResponse {
    #[serde(rename = "response")]
    pub response: Vec<models::BeamoBasicUrlResponse>,
}

impl PreSignedUrlsResponse {
    pub fn new(response: Vec<models::BeamoBasicUrlResponse>) -> PreSignedUrlsResponse {
        PreSignedUrlsResponse {
            response,
        }
    }
}

