/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviewVipBonusResponse {
    #[serde(rename = "currencies")]
    pub currencies: Vec<models::CurrencyPreview>,
}

impl PreviewVipBonusResponse {
    pub fn new(currencies: Vec<models::CurrencyPreview>) -> PreviewVipBonusResponse {
        PreviewVipBonusResponse {
            currencies,
        }
    }
}

