/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PromotableType {
    #[serde(rename = "Content")]
    Content,
    #[serde(rename = "Microservices")]
    Microservices,

}

impl std::fmt::Display for PromotableType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Content => write!(f, "Content"),
            Self::Microservices => write!(f, "Microservices"),
        }
    }
}

impl Default for PromotableType {
    fn default() -> PromotableType {
        Self::Content
    }
}

