/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmAssociation {
    #[serde(rename = "realmId", skip_serializing_if = "Option::is_none")]
    pub realm_id: Option<String>,
    #[serde(rename = "playerId", skip_serializing_if = "Option::is_none")]
    pub player_id: Option<i64>,
}

impl RealmAssociation {
    pub fn new() -> RealmAssociation {
        RealmAssociation {
            realm_id: None,
            player_id: None,
        }
    }
}
