/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmsBasicRealmConfigResponse {
    #[serde(rename = "config")]
    pub config: std::collections::HashMap<String, String>,
}

impl RealmsBasicRealmConfigResponse {
    pub fn new(config: std::collections::HashMap<String, String>) -> RealmsBasicRealmConfigResponse {
        RealmsBasicRealmConfigResponse {
            config,
        }
    }
}

