/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmsBasicWebSocketConfiguration {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

impl RealmsBasicWebSocketConfiguration {
    pub fn new(provider: String) -> RealmsBasicWebSocketConfiguration {
        RealmsBasicWebSocketConfiguration {
            provider,
            uri: None,
        }
    }
}

