/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmsBasicServicePlansResponse {
    #[serde(rename = "result")]
    pub result: Vec<models::RealmsBasicServicePlan>,
}

impl RealmsBasicServicePlansResponse {
    pub fn new(result: Vec<models::RealmsBasicServicePlan>) -> RealmsBasicServicePlansResponse {
        RealmsBasicServicePlansResponse {
            result,
        }
    }
}

