/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleAssociation {
    #[serde(rename = "realmId", skip_serializing_if = "Option::is_none")]
    pub realm_id: Option<String>,
    #[serde(rename = "roleString", skip_serializing_if = "Option::is_none")]
    pub role_string: Option<String>,
}

impl RoleAssociation {
    pub fn new() -> RoleAssociation {
        RoleAssociation {
            realm_id: None,
            role_string: None,
        }
    }
}
