/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteVariables {
    #[serde(rename = "variables")]
    pub variables: Vec<models::RouteVariable>,
}

impl RouteVariables {
    pub fn new(variables: Vec<models::RouteVariable>) -> RouteVariables {
        RouteVariables {
            variables,
        }
    }
}

