/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaveTextRequest {
    #[serde(rename = "text")]
    pub text: Vec<models::TextDefinition>,
}

impl SaveTextRequest {
    pub fn new(text: Vec<models::TextDefinition>) -> SaveTextRequest {
        SaveTextRequest {
            text,
        }
    }
}

