/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServicePlanActorServicePlansResponse {
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Vec<models::ServicePlanActorServicePlan>>,
}

impl ServicePlanActorServicePlansResponse {
    pub fn new() -> ServicePlanActorServicePlansResponse {
        ServicePlanActorServicePlansResponse {
            result: None,
        }
    }
}

