/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServicePlanActorServicePlan {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "dataDomain")]
    pub data_domain: Box<models::ServicePlanActorDataDomain>,
    #[serde(rename = "serviceLimits", skip_serializing_if = "Option::is_none")]
    pub service_limits: Option<Box<models::ServicePlanActorServiceLimits>>,
}

impl ServicePlanActorServicePlan {
    pub fn new(name: String, data_domain: models::ServicePlanActorDataDomain) -> ServicePlanActorServicePlan {
        ServicePlanActorServicePlan {
            name,
            data_domain: Box::new(data_domain),
            service_limits: None,
        }
    }
}

