/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionBasicPaymentTotal {
    #[serde(rename = "currencyCode", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<String>,
    #[serde(rename = "totalRevenue")]
    pub total_revenue: i64,
}

impl SessionBasicPaymentTotal {
    pub fn new(total_revenue: i64) -> SessionBasicPaymentTotal {
        SessionBasicPaymentTotal {
            currency_code: None,
            total_revenue,
        }
    }
}
