/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsSearchResponse {
    #[serde(rename = "ids")]
    pub ids: Vec<i64>,
}

impl StatsSearchResponse {
    pub fn new(ids: Vec<i64>) -> StatsSearchResponse {
        StatsSearchResponse {
            ids,
        }
    }
}

