/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsActorStatsSearchRequest {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "visibility")]
    pub visibility: models::StatsVisibility,
    #[serde(rename = "itemType")]
    pub item_type: String,
    #[serde(rename = "criteria", skip_serializing_if = "Option::is_none")]
    pub criteria: Option<Vec<models::StatsActorStatsSearchCriteria>>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl StatsActorStatsSearchRequest {
    pub fn new(
        domain: String,
        visibility: models::StatsVisibility,
        item_type: String,
    ) -> StatsActorStatsSearchRequest {
        StatsActorStatsSearchRequest {
            domain,
            visibility,
            item_type,
            criteria: None,
            offset: None,
            limit: None,
        }
    }
}
