/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatsSearchExtendedResponse {
    #[serde(rename = "results")]
    pub results: Vec<models::GetStatsResponse>,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "total")]
    pub total: i64,
}

impl StatsSearchExtendedResponse {
    pub fn new(
        results: Vec<models::GetStatsResponse>,
        offset: i32,
        limit: i32,
        total: i64,
    ) -> StatsSearchExtendedResponse {
        StatsSearchExtendedResponse {
            results,
            offset,
            limit,
            total,
        }
    }
}
