/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatStringListEntry {
    #[serde(rename = "k")]
    pub k: String,
    #[serde(rename = "v")]
    pub v: String,
}

impl StatStringListEntry {
    pub fn new(k: String, v: String) -> StatStringListEntry {
        StatStringListEntry {
            k,
            v,
        }
    }
}

