/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoragePerformance {
    #[serde(rename = "namespaces")]
    pub namespaces: Vec<models::PaNamespace>,
    #[serde(rename = "indexes")]
    pub indexes: Vec<models::BeamoActorPaSuggestedIndex>,
    #[serde(rename = "queries")]
    pub queries: Vec<models::PaSlowQuery>,
    #[serde(rename = "databaseMeasurements")]
    pub database_measurements: Box<models::BeamoActorDatabaseMeasurements>,
}

impl StoragePerformance {
    pub fn new(namespaces: Vec<models::PaNamespace>, indexes: Vec<models::BeamoActorPaSuggestedIndex>, queries: Vec<models::PaSlowQuery>, database_measurements: models::BeamoActorDatabaseMeasurements) -> StoragePerformance {
        StoragePerformance {
            namespaces,
            indexes,
            queries,
            database_measurements: Box::new(database_measurements),
        }
    }
}

