/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeRange {
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<i64>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<i64>,
}

impl TimeRange {
    pub fn new() -> TimeRange {
        TimeRange {
            from: None,
            to: None,
        }
    }
}
