/*
 * Beamable API
 *
 * Autogenerated Beamable API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@beamable.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePartyTags {
    #[serde(
        rename = "playerId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub player_id: Option<Option<String>>,
    #[serde(
        rename = "memberTags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub member_tags: Option<Option<Vec<models::Tag>>>,
}

impl UpdatePartyTags {
    pub fn new() -> UpdatePartyTags {
        UpdatePartyTags {
            player_id: None,
            member_tags: None,
        }
    }
}
